//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardDetail()
        {
            this.TransactionDatas = new HashSet<TransactionData>();
        }
    
        public int cardID { get; set; }
        public string cardNum { get; set; }
        public string cardPin { get; set; }
        public Nullable<decimal> cbalance { get; set; }
        public Nullable<int> accountID { get; set; }
    
        public virtual AccountHolder AccountHolder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionData> TransactionDatas { get; set; }
    }
}
