//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionData
    {
        public int transactionID { get; set; }
        public Nullable<System.DateTime> datemade { get; set; }
        public Nullable<decimal> cashIn { get; set; }
        public Nullable<decimal> cashOut { get; set; }
        public Nullable<int> cardID { get; set; }
    
        public virtual CardDetail CardDetail { get; set; }
    }
}
